USE [master]
GO

/****** Object:  Database [mydatabase]    Script Date: 3/17/2016 11:56:41 AM ******/
CREATE DATABASE [mydatabase] ON  PRIMARY 
( NAME = N'ETLAudit_QA', FILENAME = N'I:\SQLData\mydatabase.mdf' , SIZE = 32768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ETLAudit_QA_log', FILENAME = N'L:\SQLLogs\mydatabase_log.ldf' , SIZE = 10176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [mydatabase] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mydatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mydatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mydatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mydatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mydatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mydatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [mydatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mydatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mydatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mydatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mydatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mydatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mydatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mydatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mydatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mydatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mydatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mydatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mydatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mydatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mydatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mydatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mydatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mydatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mydatabase] SET  MULTI_USER 
GO

ALTER DATABASE [mydatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mydatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mydatabase] SET  READ_WRITE 
GO

